// Code generated by cmd/gen; DO NOT EDIT.

package ggkit

import (
	"context"

	channel "github.com/dsx137/gg-kit/internal/channel"
)

func Consume[T any](ch <-chan T, handler func(_p0 T) bool) {
	channel.Consume(ch, handler)
}

func ConsumeWithCtx[T any](ctx context.Context, ch <-chan T, handler func(_p0 T) bool) {
	channel.ConsumeWithCtx(ctx, ch, handler)
}
