// Code generated by cmd/gen; DO NOT EDIT.

package ggkit

import (
	"sync"

	concurrent "github.com/dsx137/gg-kit/internal/concurrent"
)

type KeyedLocker[K comparable] = concurrent.KeyedLocker[K]
type ReusePool[T any] = concurrent.ReusePool[T]
type ShardedLocker[K comparable] = concurrent.ShardedLocker[K]

func NewKeyedLocker[K comparable]() *KeyedLocker[K] {
	return concurrent.NewKeyedLocker[K]()
}

func NewReusePool[T any](factory func() (*T, error), validator func(_p0 *T) bool, closer func(_p0 *T) error) (*ReusePool[T], error) {
	return concurrent.NewReusePool(factory, validator, closer)
}

func NewShardedLocker[K comparable](exp uint, hash func(_p0 K) uint64) *ShardedLocker[K] {
	return concurrent.NewShardedLocker(exp, hash)
}

func WithLock(locker sync.Locker, f func()) {
	concurrent.WithLock(locker, f)
}

func WithLockResult[T any](locker sync.Locker, f func() T) T {
	return concurrent.WithLockResult(locker, f)
}

func WithLockResultAndError[T any](locker sync.Locker, f func() (T, error)) (T, error) {
	return concurrent.WithLockResultAndError(locker, f)
}
