// Code generated by cmd/gen; DO NOT EDIT.

package ggkit

import (
	"sync"

	concurrent "github.com/dsx137/gg-kit/internal/concurrent"
)

type ReusePool[T any] = concurrent.ReusePool[T]

func NewReusePool[T any](factory func() (*T, error), validator func(_p0 *T) bool, closer func(_p0 *T) error) (*ReusePool[T], error) {
	return concurrent.NewReusePool(factory, validator, closer)
}

func WithLock(locker sync.Locker, f func()) {
	concurrent.WithLock(locker, f)
}

func WithLockResult[T any](locker sync.Locker, f func() T) T {
	return concurrent.WithLockResult(locker, f)
}

func WithLockResultAndError[T any](locker sync.Locker, f func() (T, error)) (T, error) {
	return concurrent.WithLockResultAndError(locker, f)
}
