// Code generated by cmd/gen; DO NOT EDIT.

package ggkit

import generic "github.com/dsx137/gg-kit/internal/generic"

type Atomic[T any] = generic.Atomic[T]
type Element[T any] = generic.Element[T]
type List[T any] = generic.List[T]
type SyncMap[K comparable, V any] = generic.SyncMap[K, V]
type SyncPool[T any] = generic.SyncPool[T]

func NewAtomic[T any]() *Atomic[T] {
	return generic.NewAtomic[T]()
}

func NewAtomicWithValue[T any](val T) *Atomic[T] {
	return generic.NewAtomicWithValue(val)
}

func NewList[T any]() *List[T] {
	return generic.NewList[T]()
}

func NewSyncMap[K comparable, V any]() *SyncMap[K, V] {
	return generic.NewSyncMap[K, V]()
}

func NewSyncPool[T any](new func() T) *SyncPool[T] {
	return generic.NewSyncPool(new)
}
