// Code generated by cmd/gen; DO NOT EDIT.

package ggkit

import lang "github.com/dsx137/gg-kit/internal/lang"

func Bind[T any](f func(x any)) *T {
	return lang.Bind[T](f)
}

func BindPtr[T any](f func(x any)) *T {
	return lang.BindPtr[T](f)
}

func BindPtrR[T any, R any](f func(x any) R) (*T, R) {
	return lang.BindPtrR[T, R](f)
}

func BindR[T any, R any](f func(x any) R) (*T, R) {
	return lang.BindR[T, R](f)
}

func GetGoroutineId() int {
	return lang.GetGoroutineId()
}

func Useless(v any) {
	lang.Useless(v)
}
