// Code generated by cmd/gen; DO NOT EDIT.

package ggkit

import structure "github.com/dsx137/gg-kit/internal/structure"

type Queue[T any] = structure.Queue[T]

func NewQueue[T any]() *Queue[T] {
	return structure.NewQueue[T]()
}
