// Code generated by cmd/gen; DO NOT EDIT.

package ggkit

import util "github.com/dsx137/gg-kit/internal/util"

const ReadableChars = util.ReadableChars

func GenerateBase64Key(length int) (string, error) {
	return util.GenerateBase64Key(length)
}

func GenerateHexKey(length int) (string, error) {
	return util.GenerateHexKey(length)
}

func GenerateRandomBytes(n int) ([]byte, error) {
	return util.GenerateRandomBytes(n)
}

func GenerateReadableKey(length int, groupSize int) (string, error) {
	return util.GenerateReadableKey(length, groupSize)
}
